Repository slic3r/Slic3r, pull requests merged in 2018-11, with the labels that each got.

#4575 Enable Controller by default and prompt user for reactivation in case they try to open it from the menubar
  lib/Slic3r/GUI.pm
  lib/Slic3r/GUI/MainFrame.pm
  src/GUI/Settings.hpp
Labels: Host/Controller, UI: Misc

#4577 Add [filament_extruder_id] and revert work done for [filament_settings_id]
  lib/Slic3r/GUI/PresetEditor.pm
  lib/Slic3r/Print/GCode.pm
  xs/src/libslic3r/PrintConfig.cpp
  xs/src/libslic3r/PrintConfig.hpp
  xs/src/libslic3r/PrintGCode.cpp
Labels: Custom GCode, GCode Export

#4579 Improvements to make_dmg.sh
  package/osx/make_dmg.sh
  package/osx/plist.sh
Labels: OS: OSX, Packaging

#4590 Rename "Extended GUI" to "Rotation controls" and simplify it
  lib/Slic3r/GUI.pm
  lib/Slic3r/GUI/ColorScheme.pm
  lib/Slic3r/GUI/Plater.pm
  lib/Slic3r/GUI/Preferences.pm
Labels: UI: Misc

#4612 Update catch to 2.4.2
  src/CMakeLists.txt
Labels: Code Cleanup/Refactoring

#4595 Refer to manual in README
  README.md
Labels: Code Cleanup/Refactoring, UI/Documentation
