Repository slic3r/Slic3r, pull requests merged in 2019-01, with the labels that each got.

#4666 Use GCC8 instead of 4.9 for travis
  .travis.yml
  package/linux/appimage-apprun.sh
  package/linux/appimage.sh
  package/linux/build_shell.mk
  package/linux/libpaths.appimage.txt
  package/linux/travis-build-main.sh
  xs/src/libslic3r/ConfigBase.hpp
  xs/src/libslic3r/GCodeSender.hpp
Labels: OS: Linux, Packaging

#4672 Fix division by zero when min=max layer heights
  lib/Slic3r/Config.pm
  lib/Slic3r/GUI/Plater/SplineControl.pm
  lib/Slic3r/GUI/PresetEditor.pm
Labels: Adaptive Slicing, Crash Bug :-(

#4680 Cleanup old branch builds
  package/deploy/sftp-symlink.sh
  package/deploy/sftp.sh
  package/deploy/winscp.ps1
  package/osx/make_dmg.sh
  package/win/package_win32.ps1
  src/test/libslic3r/test_print.cpp
  xs/src/libslic3r/PrintObject.cpp
Labels: Packaging

#4669 Fix skirt/Brim
  src/test/libslic3r/test_skirt_brim.cpp
  src/test/test_data.hpp
  xs/src/libslic3r/Print.cpp
  xs/src/libslic3r/Print.hpp
  xs/src/libslic3r/PrintGCode.cpp
Labels: Code Cleanup/Refactoring

#4679 Patch for #4620 - ensure posDetectSurfaces is invalidated on slice change
  src/test/libslic3r/test_print.cpp
  xs/src/libslic3r/PrintObject.cpp
Labels: Perimeters

#4691 brim ears
  lib/Slic3r/GUI/PresetEditor.pm
  slic3r.pl
  src/GUI/Dialogs/PresetEditor.hpp
  src/test/libslic3r/test_skirt_brim.cpp
  xs/src/libslic3r/Print.cpp
  xs/src/libslic3r/PrintConfig.cpp
  xs/src/libslic3r/PrintConfig.hpp
Labels: Support material
